app_wallet/app_wallet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wallets/', include('wallets.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('coins.urls')),
    
]

app_wallet/coins/urls.py
from django.urls import path

from coins import views


app_name = 'coins'

urlpatterns=[
	path('', views.coins_view, name='coins'),
	path('create/', views.create_view, name='create'),
	path('<int:coin_id>/', views.coin_detail, name='coin')
]

app_wallet/wallets/urls.py
from django.urls import path
from wallets import views

app_name = 'wallets'

urlpatterns = [
	path('', views.user_wallets_view, name='wallets'),
	path('wallet/<int:wallet_id>/', views.wallet_view, name='wallet'),
	path('wallet/<int:wallet_id>/update/', views.update_view, name='update'),
	path('create/', views.create_view, name='create'),
]

app_wallet/wallets/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.



class MainWallet(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, null=False, blank=False, on_delete=models.CASCADE)





class Wallet(models.Model):

	LEVELS_OF_EXPERIENCE = [
		('FRESH', 'Fresh'),
		('INTERMEDIATE', 'Intermediate'),
		('EXPERT', 'Expert')
	]

	main_wallet = models.ForeignKey(MainWallet, on_delete=models.CASCADE, null=False)
	name = models.CharField(max_length=16, null=False, blank=False)
	wallet_id = models.CharField(max_length=32, unique=True, null=False, blank=False)
	user_experience = models.CharField(max_length=12, choices=LEVELS_OF_EXPERIENCE, default='FRESH')
	yang = models.IntegerField(validators=[MinValueValidator(0)], default=0)
	active = models.BooleanField(default=False)
	

	def __str__(self):
		return f'{self.name}, {self.user_experience} '


	def get_absolute_url(self):
		return reverse('wallets:wallet', kwargs={'wallet_id': self.id})


	def clean(self):
		#If wallet is updated
		if self.id is not None:
			is_any_other_wallet_active = Wallet.objects.filter(main_wallet=self.main_wallet, active=True).exclude(id=self.id)
			if is_any_other_wallet_active:
				raise ValidationError(f'{is_any_other_wallet_active.first().name} is active')

			is_wallet_name_unique = Wallet.objects.filter(main_wallet=self.main_wallet, name__iexact=self.name).exclude(id=self.id)
			if is_wallet_name_unique:
				raise ValidationError(f'{self.name} is already taken.')

	






@receiver(post_save, sender=User)
def create_user_wallet(sender, instance, created, **kwargs):
	if created:
		MainWallet.objects.create(user=instance)

app_wallet/wallets/forms.py
from django import forms
from django.contrib.auth import get_user_model
from wallets.models import Wallet
from django.core.exceptions import ValidationError

class CreateWalletForm(forms.ModelForm):
	name = forms.CharField(label='Name', widget=forms.TextInput(attrs={'placeholder': 'Name'}))
	wallet_id = forms.CharField(label='Wallet ID', widget=forms.TextInput(attrs={'placeholder': 'Id'}))

	class Meta:
		model = Wallet
		fields = ['name', 'wallet_id', 'user_experience']

	def __init__(self, *args, **kwargs):
		self.user = kwargs.pop('user')
		super(CreateWalletForm, self).__init__(*args, **kwargs)
		
	#If wallet is created  form clean does work 
	def clean(self):
		wallet_names = Wallet.objects.filter(main_wallet__user=self.user, name__iexact=self.cleaned_data['name']).exists()
		if wallet_names:
			raise ValidationError('name is already taken')

		return self.cleaned_data






#If wallet is updated model validation works
class UpdateWalletForm(forms.ModelForm):
	name = forms.CharField(label='Name', widget=forms.TextInput(attrs={'placeholder': 'Name'}))
	wallet_id = forms.CharField(label='Wallet ID', widget=forms.TextInput(attrs={'placeholder': 'Id'}))

	class Meta:
		model = Wallet
		fields = ['name', 'wallet_id', 'user_experience', 'active']

	

app_wallet/wallets/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.core.exceptions import ValidationError

from wallets.models import Wallet, MainWallet
from wallets.forms import CreateWalletForm, UpdateWalletForm
from coins.models import CoinHolder

# Create your views here.


@login_required
def user_wallets_view(request):
	wallets = Wallet.objects.filter(main_wallet__user=request.user.id) # sproboj napisac to na modelu
	context = {
		'wallets': wallets,
	}

	return render(request, 'wallets/user_wallets.html', context=context)


@login_required
def wallet_view(request, wallet_id):
	wallet = get_object_or_404(Wallet, id=wallet_id)
	coins = CoinHolder.objects.filter(holder_wallet=wallet)
	context = {
		'wallet': wallet,
		'coins': coins
	} 
	if request.POST.get('delete') == 'Delete':
		wallet.delete()
		return redirect(reverse('wallets:wallets'))

	elif request.POST.get('Boost') == '+':
		wallet.yang += 1000
		wallet.save()
		return redirect(reverse('wallets:wallet', kwargs={'wallet_id': wallet_id}))

	return render(request, 'wallets/wallet.html', context=context)

@login_required
def create_view(request):
	
	form = CreateWalletForm(request.POST or None, user=request.user)
	main_wallet = MainWallet.objects.get(user=request.user)

	if form.is_valid():
		obj = form.save(commit=False) 
		obj.main_wallet = main_wallet
		obj.save()
		return redirect(obj) # redirect use get_absolute_url written in model

	context = {
		'form': form
	}

	return render(request, 'wallets/create.html', context=context)


@login_required
def update_view(request, wallet_id):
	wallet = get_object_or_404(Wallet, id=wallet_id)
	form = UpdateWalletForm(request.POST or None, instance=wallet)
	context = {
		'form': form,
	}
	if form.is_valid():
		form.save()
		return redirect(wallet)
	return render(request, 'wallets/update.html', context=context)

app_wallet/wallets/templates/wallets/create.html
{% extends 'main_layout.html' %}



{% block main %}


	<form method='POST'>
		{% csrf_token %}
		{{form.as_p}}
		<input type='hidden' name='user_id' value="{{request.user.id}}">
		<input type='submit' value='Create!'>
	</form>

{% endblock %}

app_wallet/wallets/templates/wallets/update.html
{% extends 'main_layout.html' %}

{% block head %}

{% endblock %}

{% block main %}

	<form method='POST'>
		{% csrf_token %}
		{{form.as_p}}
		<input type='submit' value='Update Wallet'>
	</form>

{% endblock %}

app_wallet/wallets/templates/wallets/user_wallets.html
{% extends 'main_layout.html' %}

{% block main %}

	<h1>
		Welcome, {{request.user.username}}
	</h1>
	{% for wallet in wallets %}

		<h3><a href="{{wallet.get_absolute_url}}">{{wallet}}</a></h3>

	{% empty %}

	No wallets, would you like to create one? <a href="{% url 'wallets:create' %}">Click here</a>

	{% endfor %}	

{% endblock %}

app_wallet/wallets/templates/wallets/wallet.html
{% extends 'main_layout.html' %}

{% block head %}



{% endblock %}


{% block main %}


	<h1>
		{{wallet}}
	</h1>

	<h3>
		Yang: {{wallet.yang}} | Wallet has not enough money? Add demo Yang 
		<form method='POST' style="display:inline-block;"> {% csrf_token %} <input type='submit' name='Boost' value='+'> </form> 
	</h3>
	<h3>
		Active: {{wallet.active}}
	</h3>

	<h3>
		<p>
			Coins:
		</p>	
		{% for coin in coins %}
			<p>
				{{coin.coin}}, Avg buy: {{coin.avg_buy_price}} Amount: {{coin.amount_of_coin}}
			</p>
		{% empty %}
			You have 0 coins, check available coins! <a href="{% url 'coins:coins' %}"> Click here </a>
		{% endfor %}
		
	</h3>
	<form method='POST'>
		{% csrf_token %}
		<input type='submit' name='delete' value='Delete'>
	</form>
	<form action="{% url 'wallets:update' wallet.id %}">
		<input type='submit' value='Update'>
	</form>


{% endblock %}