app_wallet/accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
	path('create/', views.create_view, name='create'),
	path('login/', views.login_view, name='login'),
	path('logout/', views.logout_view, name='logout')
]

app_wallet/app_wallet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wallets/', include('wallets.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('coins.urls')),
    
]

app_wallet/coins/urls.py
from django.urls import path

from coins import views


app_name = 'coins'

urlpatterns=[
	path('', views.coins_view, name='coins'),
	path('create/', views.create_view, name='create'),
	path('<int:coin_id>/', views.coin_detail, name='coin')
]

app_wallet/wallets/urls.py
from django.urls import path
from wallets import views

app_name = 'wallets'

urlpatterns = [
	path('', views.user_wallets_view, name='wallets'),
	path('wallet/<int:wallet_id>/', views.wallet_view, name='wallet'),
	path('wallet/<int:wallet_id>/update/', views.update_view, name='update'),
	path('create/', views.create_view, name='create'),
]

app_wallet/templates/main_layout.html
<!DOCTYPE HTML>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		{% block head %}
		
		{% endblock %}

	</head>
	<body>
		<style>
			body {
				margin:0;
				text-align:center;
			}

			ul {
				list-style-type: none;
				margin: 0;
				padding: 0;
				overflow: hidden;
				background-color: #333333;
				}
			li {
				float: left;
			}

			li a {
			  display: block;
			  color:white;
			  text-align: center;
			  padding: 16px;
			  text-decoration: none;
			}

		</style>
		<ul>
			<li>
				<a href="{% url 'coins:coins' %}"> AppWallet </a>
			</li>
			<li>
				<a href="{% url 'coins:create' %}"> Create Coin </a>
			</li>
			<li> 
				<a href="{% url 'accounts:create' %}"> Sign Up </a>
			</li>
			<li>
				<a href="{% url 'accounts:login' %}"> Login </a>
			</li>
			{% if request.user.is_authenticated %} 
			<li>
				<a href="{% url 'accounts:logout' %}"> Logout </a> 
			</li>
			{% endif %}
			<li>
				<a href="{% url 'wallets:wallets' %}"> Wallets </a>
			</li>
			<li> 
				<a href="{% url 'wallets:create' %}"> New Wallet </a>
			</li>
		</ul>
		{% block main %}



		{% endblock %}

	</body>
</html>